### ISSUE TITLE
Cannot use req as type

### ISSUE THREAD

**Issue by RetryingOOS** [zMrKrabz/fhttp#2]
Replaced "net/http" with http "github.com/zMrKrabz/fhttp"

```golang
 cannot use req (type *"github.com/zMrKrabz/fhttp".Request) as type *"net/http".Request in argument to h2clientConn.RoundTrip
```

nvm just had to replace all imports in net

**Comment by gotsteez** [comment]
Check example_client_test.go to see how to implement http2
